### ISSUE TITLE
Does steemconnect check the signed transactions against requested scope?

### ISSUE THREAD

**Issue by Jblew** [bonustrack/steemconnect#419]
### Expected behavior
I would expect steemconnect to verify signed transactions against the requested scope.

### Actual behavior
With previous version of steemconnect we had a logic for requesting scope escalation. The new base64 token no longer contains information about scope. Also, I cannot find any scope checking in the steemconnect repo.

I can see in https://github.com/bonustrack/steemconnect/blob/c46e294fa181d250bb3050071ece18fcbfab2fbf/src/views/LoginRequest.vue#L100 and https://github.com/bonustrack/steemconnect/blob/b61cb40c38af0cca7b98186a9374237dfb2e6a56/src/router.js#L48 that during login the only valid scopes are `login` and `posting`. Am I right that now the transactions are not checked against the scope? If yes, then why?

**Comment by bgornicki** [comment]
Same question here, I was using different scopes in [Engrave](https://github.com/wise-team/engrave) (for blog readers and blog administrators) and now I cannot distinguish `access_tokens` between these two roles.

**Comment by bonustrack** [comment]
We don't support segmented posting permission anymore, the scope is now either `login` or `posting`. The reason is that we've moved from having app accounts managed by SC to having them managed by the apps directly, with that we can not completely insure for users that the app will only use his posting authority to broadcast an operation out of a scope with segmented posting permission. This can be misleading for users. IMO segmented permissions would fit better if it were implemented directly at the protocol level.
